/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-SCARD.h
 #	source generated by 4D Plugin Wizard
 #	Project : SCARD
 #	author : miyako
 #	2022/01/26
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_SCARD_H
#define PLUGIN_SCARD_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"

#include "json/json.h"

#if VERSIONMAC
#import <Cocoa/Cocoa.h>
#import <Security/Security.h>
#import <CryptoTokenKit/CryptoTokenKit.h>
static bool checkAccess(PA_ObjectRef status);
#endif

#include <thread>
#include <mutex>
#include <future>

#define TK_USLEEP_DURATION_FOR_POLLING 25000
#define TK_USLEEP_DURATION 2500  //microseconds

#define DEFAULT_TIMEOUT_MS_FOR_RESOURCE_MANAGER 5000
#define LIBPCSC_API_TIMEOUT 2000
#define SCARD_API_TIMEOUT 1

#pragma mark -

void SCARD_Get_readers(PA_PluginParameters params);
void SCARD_Read_tag(PA_PluginParameters params);
void SCARD_Get_status(PA_PluginParameters params);

static void u8_to_u16(std::string& u8, CUTF16String& u16);
static void u16_to_u8(CUTF16String& u16, std::string& u8);

#endif /* PLUGIN_SCARD_H */
